#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# load Z
source `brew --prefix`/etc/profile.d/z.sh

# put time in right prompt if this works
RPROMPT="%{$fg[grey]%}[%*]" 

# #  set DEFAULT_USER to hide the “user@hostname” info when you’re logged in as yourself on your local machine.
DEFAULT_USER=elipapa